---
title: "11-19-19"
author: "Jackson Kehoe"
date: "11/19/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidymodels)
library(skimr)
library(fs)
library(rstanarm)

```

```{r}
download.file("https://github.com/TheUpshot/2018-live-poll-results/archive/master.zip", destfile = "./raw_data.zip")

unzip("./raw_data.zip")

raw_data <- read_csv("./2018-live-poll-results-master/data/elections-poll-az02-1.csv", 
                     col_types = cols(
                                      .default = col_character(),
                                      turnout_scale = col_double(),
                                      turnout_score = col_double(),
                                      w_LV = col_double(),
                                      w_RV = col_double(),
                                      final_weight = col_double(),
                                      timestamp = col_datetime(format = "")
                                    ))
```

```{r}
#This works but it's not as efficient as fs
setwd("./2018-live-poll-results-master/data")
polldata = list.files(pattern="*.csv")
file_list = lapply(polldata, read_csv)
```

```{r, cache = TRUE}
my_list <- fs::dir_ls("./2018-live-poll-results-master/data/")

raw <- map_dfr(my_list, read_csv, .id = "source", col_types = cols(
                                      .default = col_character(),
                                      turnout_scale = col_double(),
                                      turnout_score = col_double(),
                                      w_LV = col_double(),
                                      w_RV = col_double(),
                                      final_weight = col_double(),
                                      timestamp = col_datetime(format = "")
                                    ))

raw %>% count(source)

fs::file_delete(c("raw_data.zip", "2018-live-poll-results-master"))
```

```{r}
#making a table
x <- raw %>%
  mutate(dvote = ifelse(response == "Dem", 1, 0)) %>%
  mutate(female = ifelse(gender == "Female", 1, 0)) %>%
  select(dvote, response, gender) %>%
  drop_na()

sample_n(x, size = 5)
count(response)
```

```{r}
#making a model
lm(response ~ gender, x)
```

